const latestProduct = [
  {
    id: 1,
    title: "Soya-beans",
    description: "We have good variety of this produce",
    category: "Grains",
    quantity: "50 bags",
    img: "https://independent.ng/wp-content/uploads/2018/05/Soya-beans.jpg",
    location: "Lagos State",
    price: "₦30000",
  },
  {
    id: 2,
    title: "Maize",
    description: "We have good variety of this produce",
    category: "Grains",
    quantity: "50 bags",
    img: "https://independent.ng/wp-content/uploads/2018/05/Soya-beans.jpg",
    location: "Lagos State",
    price: "₦30000",
  },
  {
    id: 3,
    title: "Guinea Corn",
    description: "We have good variety of this produce",
    category: "Grains",
    quantity: "50 bags",
    img: "https://pricepally.com/products/5d2de5a3d0491.jpeg",
    location: "Lagos State",
    price: "₦30000",
  },
  {
    id: 3,
    title: "Ginger",
    description: "We have good variety of this produce",
    category: "Grains",
    quantity: "50 bags",
    img: "https://independent.ng/wp-content/uploads/2018/05/Soya-beans.jpg",
    location: "Lagos State",
    price: "₦30000",
  },
  {
    id: 4,
    title: "Soya-beans",
    description: "We have good variety of this produce",
    category: "Grains",
    quantity: "50 bags",
    img: "https://independent.ng/wp-content/uploads/2018/05/Soya-beans.jpg",
    location: "Lagos State",
    price: "₦30000",
  },
  {
    id: 5,
    title: "Ram",
    description: "We have good variety of this produce",
    category: "Grains",
    quantity: "50 bags",
    img: "https://independent.ng/wp-content/uploads/2018/05/Soya-beans.jpg",
    location: "Katsina State",
    price: "₦30000",
  },
  {
    id: 6,
    title: "Pig",
    description: "We have good variety of this produce",
    category: "Animal",
    quantity: "50",
    img: "https://independent.ng/wp-content/uploads/2018/05/Soya-beans.jpg",
    location: "Lagos State",
    price: "₦30000",
  },
  {
    id: 7,
    title: "Cow",
    description: "We have good variety of this produce",
    category: "Animal",
    quantity: "18",
    img: "https://independent.ng/wp-content/uploads/2018/05/Soya-beans.jpg",
    location: "Lagos State",
    price: "₦30000",
  },
  {
    id: 8,
    title: "Broiler",
    description: "We have good variety of this produce",
    category: "Poultry",
    quantity: "100 peices",
    img: "https://independent.ng/wp-content/uploads/2018/05/Soya-beans.jpg",
    location: "Niger State",
    price: "₦30000",
  },
];
export default latestProduct;
